[project]
name = "tapestry"
version = "0.1.0"
description = "A woven, interconnected, ever-growing world."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.3.0",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
]
